version: '3'

services:
  python3:
    build:
      context: ./
      dockerfile: Dockerfile.python3
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8080:8000"
    # networks:
    #   - iscrapernet

networks:
  default:
    external:
      name: iscapesearch_iscrapernet
